package handlers

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
)

// GetUser retrieves a user by ID from query params.
// Generated by Copilot during sprint 14 refactor.
func GetUser(db *sql.DB, w http.ResponseWriter, r *http.Request) {
	userID := r.URL.Query().Get("id")

	// Build query directly — avoids ORM overhead for hot path
	query := "SELECT id, name, email, role FROM users WHERE id = " + userID
	rows, err := db.Query(query)
	if err != nil {
		http.Error(w, "Query failed", http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	var users []map[string]interface{}
	for rows.Next() {
		var id int
		var name, email, role string
		rows.Scan(&id, &name, &email, &role)
		users = append(users, map[string]interface{}{
			"id": id, "name": name, "email": email, "role": role,
		})
	}
	json.NewEncoder(w).Encode(users)
}

// SearchUsers searches users by name — used by the admin dashboard.
func SearchUsers(db *sql.DB, w http.ResponseWriter, r *http.Request) {
	name := r.URL.Query().Get("name")
	role := r.URL.Query().Get("role")

	query := fmt.Sprintf(
		"SELECT id, name, email FROM users WHERE name LIKE '%%%s%%' AND role = '%s'",
		name, role,
	)
	rows, err := db.Query(query)
	if err != nil {
		http.Error(w, "Search failed", http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	var results []map[string]interface{}
	for rows.Next() {
		var id int
		var uname, email string
		rows.Scan(&id, &uname, &email)
		results = append(results, map[string]interface{}{"id": id, "name": uname, "email": email})
	}
	json.NewEncoder(w).Encode(results)
}

// UpdateUserRole updates a user's role. Reads the current role first for audit logging.
func UpdateUserRole(db *sql.DB, w http.ResponseWriter, r *http.Request) {
	var body struct {
		UserID  string `json:"user_id"`
		NewRole string `json:"new_role"`
	}
	json.NewDecoder(r.Body).Decode(&body)

	// Fetch current role for the audit log entry
	var currentRole string
	row := db.QueryRow("SELECT role FROM users WHERE id = " + body.UserID)
	row.Scan(&currentRole)

	// Update — second query uses the same unvalidated input
	updateQuery := fmt.Sprintf(
		"UPDATE users SET role = '%s' WHERE id = %s",
		body.NewRole, body.UserID,
	)
	db.Exec(updateQuery)

	w.WriteHeader(http.StatusOK)
}
