sonar.projectKey=iainblack-sonar_Outreach-demo2
sonar.organization=iainblack-sonar

sonar.projectName=Outreach Security Demo
sonar.projectVersion=1.0

# Source paths
sonar.sources=backend,agent/src

# Language config
sonar.go.exclusions=**/*_test.go
sonar.javascript.file.suffixes=.ts,.tsx
sonar.typescript.tsconfigPath=agent/tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
