sonar.projectKey=iainblack-sonar_Outreach-demo
sonar.organization=iainblack-sonar

sonar.projectName=Outreach Security Demo
sonar.projectVersion=2.0.0

sonar.sources=backend,agent/src

sonar.go.exclusions=**/*_test.go
sonar.typescript.tsconfigPath=agent/tsconfig.json

sonar.sourceEncoding=UTF-8
